version: '3.3'

services:
  drupal:
    build: ./php
    container_name: apache-5.6
    depends_on:
      - mysql
      - mariadb
    volumes:
      - ./drupal:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini:rw
      - ./apache2/conf:/etc/apache2/sites-enabled/
      - ./apache2/logs:/var/log/apache2/
    restart: always
    ports:
      - 80:80


  mysql:
    image: mysql:5.7.39
    container_name: mysql

    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=drupal
    volumes:
      - type: bind
        source:  ./mysql/my.cnf
        target: /etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=drupal
    volumes:
      - type: bind
        source:  ./mariadb/my.cnf
        target: /etc/mariadb/my.cnf
      - ./mariadb/data:/var/lib/mysql
    restart: always
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
  solr:
    image: solr
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    restart: always
volumes:
  data:
